CREATE DATABASE Fletes4003;

USE Fletes4003;

CREATE TABLE CUSTOMER (

    PROVID INT(10) UNIQUE NOT NULL AUTO_INCREMENT ,
    PROVRFC VARCHAR(20) PRIMARY KEY ,
    PROVNAME VARCHAR(50),
    PROVRAZONSOCIAL VARCHAR(50),
    PROVADDRESS VARCHAR(50),
    PROVSTATE VARCHAR(50),
    PROVCITY VARCHAR(50),
    PROVZIP VARCHAR(10),
    PROVCOUNTRY VARCHAR(50),
    PROVNUM VARCHAR(10),
    PROVEMAIL VARCHAR(50) UNIQUE,
    PROVPASS VARCHAR(150),
    PROVPHONE VARCHAR(50),
    PROVTYPE VARCHAR(20),
    PROVUSERDATA VARCHAR(10)
    
);

CREATE TABLE TICKETS(
    TICKETID INT AUTO_INCREMENT PRIMARY KEY,
    PROVCARGAADDRESS VARCHAR(100),
    PROVENTREGAADDRESS VARCHAR(100),
    PROVCARGATIME VARCHAR(10), 
    PROVCARGADATE VARCHAR(10), 
    PROVENTREGACLIENTTIME VARCHAR(10), 
    PROVENTREGACLIENTDATE VARCHAR(10), 
    PROVPEMEXLLEGADATIME VARCHAR(10),
    PROVPEMEXLLEGADADATE VARCHAR(10),
    PROVPEMEXSALIDATIME VARCHAR(10),
    PROVPEMEXSALIDADATE VARCHAR(10),
    PROVSALIDACLIENTTIME VARCHAR(10),
    PROVSALIDACLIENTDATE VARCHAR(10),
    PROVGEOCERCA VARCHAR(50),
    PROVKILOMETRAJE INT(10),
    PROVSELLO VARCHAR(50),
    PROVTANQUE VARCHAR(50),            
    PROVGASTOS INT(50),
    PROVOBSERVACIONES VARCHAR(50),
    PROVPRODUCT VARCHAR(50), 
    PROVCANTIDAD INT(50),
    PROVEMPRESA VARCHAR(50),
    PROVSTATUS VARCHAR(50),
    PROVUNIDAD VARCHAR(50),
    PROVASIGN VARCHAR(50),
    PROVCOSTO INT(50),
    PROVCHOFER VARCHAR(50),
    PROVTIPO VARCHAR(50),
    PROVCP VARCHAR(50),
    PROVFACTURA VARCHAR (50),
    RFC_ID VARCHAR(50),
    FOREIGN KEY (RFC_ID) 
        REFERENCES CUSTOMER(PROVRFC)
);